import { DataTypes } from "sequelize";
import sequelize from "../config/database.js";

const AsetModel3d = sequelize.define(
  "AsetModel3d",
  {
    id_model_3d: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    id_aset: { type: DataTypes.INTEGER, allowNull: false },
    version: { type: DataTypes.INTEGER, allowNull: false },
    is_active: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true },
    status: { type: DataTypes.STRING(20), allowNull: false, defaultValue: "ready" },
    format: { type: DataTypes.STRING(12), allowNull: false },
    original_name: { type: DataTypes.STRING(255), allowNull: false },
    storage_path: { type: DataTypes.TEXT, allowNull: false },
    public_url: { type: DataTypes.TEXT, allowNull: false },
    mime_type: { type: DataTypes.STRING(100), allowNull: false },
    file_size_bytes: { type: DataTypes.BIGINT, allowNull: false },
    checksum_sha256: { type: DataTypes.STRING(64), allowNull: false },
    conversion_status: { type: DataTypes.STRING(20), allowNull: false, defaultValue: "pending" },
    converted_storage_path: { type: DataTypes.TEXT, allowNull: true },
    converted_public_url: { type: DataTypes.TEXT, allowNull: true },
    converted_mime_type: { type: DataTypes.STRING(100), allowNull: true },
    converted_size_bytes: { type: DataTypes.BIGINT, allowNull: true },
    converted_checksum_sha256: { type: DataTypes.STRING(64), allowNull: true },
    converted_at: { type: DataTypes.DATE, allowNull: true },
    conversion_error: { type: DataTypes.TEXT, allowNull: true },
    converted_bounds: { type: DataTypes.JSONB, allowNull: true },
    converted_triangle_count: { type: DataTypes.BIGINT, allowNull: true },
    lod_medium_storage_path: { type: DataTypes.TEXT, allowNull: true },
    lod_medium_public_url: { type: DataTypes.TEXT, allowNull: true },
    lod_medium_size_bytes: { type: DataTypes.BIGINT, allowNull: true },
    lod_medium_checksum_sha256: { type: DataTypes.STRING(64), allowNull: true },
    lod_medium_triangle_count: { type: DataTypes.BIGINT, allowNull: true },
    lod_low_storage_path: { type: DataTypes.TEXT, allowNull: true },
    lod_low_public_url: { type: DataTypes.TEXT, allowNull: true },
    lod_low_size_bytes: { type: DataTypes.BIGINT, allowNull: true },
    lod_low_checksum_sha256: { type: DataTypes.STRING(64), allowNull: true },
    lod_low_triangle_count: { type: DataTypes.BIGINT, allowNull: true },
    optimized_at: { type: DataTypes.DATE, allowNull: true },
    optimization_error: { type: DataTypes.TEXT, allowNull: true },
    kml_entry: { type: DataTypes.STRING(500), allowNull: true },
    model_entry: { type: DataTypes.STRING(500), allowNull: true },
    model_type: { type: DataTypes.STRING(12), allowNull: true },
    location_lat: { type: DataTypes.DECIMAL(10, 8), allowNull: true },
    location_long: { type: DataTypes.DECIMAL(11, 8), allowNull: true },
    altitude_m: { type: DataTypes.DECIMAL(10, 3), allowNull: true },
    altitude_mode: { type: DataTypes.STRING(40), allowNull: true },
    heading: { type: DataTypes.DECIMAL(10, 5), allowNull: true },
    tilt: { type: DataTypes.DECIMAL(10, 5), allowNull: true },
    roll: { type: DataTypes.DECIMAL(10, 5), allowNull: true },
    scale_x: { type: DataTypes.DECIMAL(12, 6), allowNull: true },
    scale_y: { type: DataTypes.DECIMAL(12, 6), allowNull: true },
    scale_z: { type: DataTypes.DECIMAL(12, 6), allowNull: true },
    entry_count: { type: DataTypes.INTEGER, allowNull: false, defaultValue: 0 },
    manifest: { type: DataTypes.JSONB, allowNull: false, defaultValue: {} },
    uploaded_by: { type: DataTypes.INTEGER, allowNull: true },
    uploaded_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
    archived_at: { type: DataTypes.DATE, allowNull: true },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
  },
  { tableName: "aset_model_3d", timestamps: false },
);

export default AsetModel3d;
